version: '3'
services:
    octoprint:
        container_name: octoprint
        build: ./octoprint/
        ports:
          - 5000:5000
        devices:
          - /dev/ttyACM0:/dev/ttyACM0
        volumes:
          - ./config:/home/octoprint/.octoprint

    mjpg:
        build: ./streamer/
        ports:
            - 8080:8080
        devices:
            - /dev/video0:/dev/video0
